/* eslint-disable no-unused-vars */

export enum EWizzardPage {
  LANDING_PAGE = 'LANDING_PAGE',
  CONFIGURATOR_PAGE = 'CONFIGURATOR_PAGE',
  OVERVIEW_PAGE = 'OVERVIEW_PAGE',
  COMPLETION_PAGE = 'COMPLETION_PAGE',
}
